# Generated by Django 4.0.4 on 2022-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_tags_news_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
