# Generated by Django 4.0.4 on 2022-05-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_tags_options_alter_tags_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='title',
        ),
    ]
